CREATE TABLESPACE svn_data
  DATAFILE 'C:\APP\ORADATA\FREE\C_27960_Arnaud_SecurityViolationNotifier_DB\svn_data01.dbf'
  SIZE 500M
  AUTOEXTEND ON NEXT 200M MAXSIZE UNLIMITED
  EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE svn_index
  DATAFILE 'C:\APP\ORADATA\FREE\C_27960_Arnaud_SecurityViolationNotifier_DB\svn_index01.dbf'
  SIZE 200M
  AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
  EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TEMPORARY TABLESPACE svn_temp
  TEMPFILE 'C:\APP\ORADATA\FREE\C_27960_Arnaud_SecurityViolationNotifier_DB\svn_temp01.dbf'
  SIZE 200M
  AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
