-- Safely drop table if it exists
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE operations_log CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN -- ORA-00942: table or view does not exist
         RAISE;
      END IF;
END;
/

-- Create the operations_log table
CREATE TABLE operations_log (
    log_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        NUMBER NOT NULL,
    operation      VARCHAR2(50) NOT NULL,
    target_table   VARCHAR2(100),
    timestamp      DATE DEFAULT SYSDATE,
    details        VARCHAR2(400),
    CONSTRAINT fk_log_user FOREIGN KEY (user_id)
        REFERENCES users(user_id)
);
