CREATE TABLE security_policies (
    policy_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_name    VARCHAR2(100) NOT NULL UNIQUE,
    description    VARCHAR2(400),
    created_at     DATE DEFAULT SYSDATE
);
