CREATE TABLE users (
    user_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username       VARCHAR2(50) NOT NULL UNIQUE,
    role_name      VARCHAR2(50) NOT NULL,
    created_at     DATE DEFAULT SYSDATE
);
