CREATE TABLE violations (
    violation_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_id         NUMBER NOT NULL,
    policy_id      NUMBER NOT NULL,
    detected_at    DATE DEFAULT SYSDATE,
    severity       VARCHAR2(20),
    status         VARCHAR2(20) DEFAULT 'UNRESOLVED',
    CONSTRAINT fk_violation_log FOREIGN KEY (log_id)
        REFERENCES operations_log(log_id),
    CONSTRAINT fk_violation_policy FOREIGN KEY (policy_id)
        REFERENCES security_policies(policy_id)
);
